# TCL File Generated by Component Editor 18.1
# Fri Nov 01 11:12:41 CET 2019
# DO NOT MODIFY


# 
# lcd_dma "lcd_dma" v1.0
#  2019.11.01.11:42:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd_dma
# 
set_module_property DESCRIPTION ""
set_module_property NAME lcd_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lcd_dma
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_dma
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd_dma_entity.vhdl VHDL PATH ../vhdl_modules/lcd_controller/lcd_dma_entity.vhdl
add_fileset_file dma_controller_entity.vhdl VHDL PATH ../vhdl_modules/lcd_controller/dma_controller_entity.vhdl
add_fileset_file dma_controller_behavior.vhdl VHDL PATH ../vhdl_modules/lcd_controller/dma_controller_behavior.vhdl
add_fileset_file pixel_formatter_entity.vhdl VHDL PATH ../vhdl_modules/lcd_controller/pixel_formatter_entity.vhdl
add_fileset_file pixel_formatter_behavior.vhdl VHDL PATH ../vhdl_modules/lcd_controller/pixel_formatter_behavior.vhdl
add_fileset_file send_receive_if_entity.vhdl VHDL PATH ../vhdl_modules/lcd_controller/send_receive_if_entity.vhdl
add_fileset_file send_receive_if_behavior.vhdl VHDL PATH ../vhdl_modules/lcd_controller/send_receive_if_behavior.vhdl
add_fileset_file lcd_dma_behavior.vhdl VHDL PATH ../vhdl_modules/lcd_controller/lcd_dma_behavior.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset Reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 3
add_interface_port slave slave_cs chipselect Input 1
add_interface_port slave slave_rd read Input 1
add_interface_port slave slave_read_data readdata Output 32
add_interface_port slave slave_wait_request waitrequest Output 1
add_interface_port slave slave_we write Input 1
add_interface_port slave slave_write_data writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master master_read_data_valid readdatavalid Input 1
add_interface_port master master_address address Output 32
add_interface_port master master_burst_count burstcount Output 8
add_interface_port master master_read read Output 1
add_interface_port master master_read_data readdata Input 32
add_interface_port master master_wait_request waitrequest Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clock clk Input 1


# 
# connection point external
# 
add_interface external conduit end
set_interface_property external associatedClock clock
set_interface_property external associatedReset ""
set_interface_property external ENABLED true
set_interface_property external EXPORT_OF ""
set_interface_property external PORT_NAME_MAP ""
set_interface_property external CMSIS_SVD_VARIABLES ""
set_interface_property external SVD_ADDRESS_GROUP ""

add_interface_port external ChipSelectBar csb Output 1
add_interface_port external DataBus db Bidir 16
add_interface_port external DataCommandBar dcb Output 1
add_interface_port external IM0 im Output 1
add_interface_port external ReadBar rb Output 1
add_interface_port external ResetBar resb Output 1
add_interface_port external WriteBar wb Output 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint slave
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq end_of_transaction_irq irq Output 1

