# TCL File Generated by Component Editor 18.1
# Fri Nov 01 11:12:41 CET 2019
# DO NOT MODIFY


# 
# i2c_master "i2c_master" v1.0
#  2019.11.01.11:42:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2c_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2c_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2c_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_avalon_slave_entity.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_avalon_slave_entity.vhdl TOP_LEVEL_FILE
add_fileset_file i2c_autodetect_behavior.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_autodetect_behavior.vhdl
add_fileset_file i2c_autodetect_entity.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_autodetect_entity.vhdl
add_fileset_file i2c_avalon_slave_behavior.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_avalon_slave_behavior.vhdl
add_fileset_file i2c_cntrl_behavior.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_cntrl_behavior.vhdl
add_fileset_file i2c_cntrl_entity.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_cntrl_entity.vhdl
add_fileset_file i2c_data_behavior.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_data_behavior.vhdl
add_fileset_file i2c_data_entity.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_data_entity.vhdl
add_fileset_file i2c_start_stop_behavior.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_start_stop_behavior.vhdl
add_fileset_file i2c_start_stop_entity.vhdl VHDL PATH ../vhdl_modules/i2c_core/i2c_start_stop_entity.vhdl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 2
add_interface_port slave slave_byte_enables byteenable Input 4
add_interface_port slave slave_cs chipselect Input 1
add_interface_port slave slave_read_data readdata Output 32
add_interface_port slave slave_we write Input 1
add_interface_port slave slave_write_data writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point i2c_port
# 
add_interface i2c_port conduit end
set_interface_property i2c_port associatedClock clock
set_interface_property i2c_port associatedReset reset
set_interface_property i2c_port ENABLED true
set_interface_property i2c_port EXPORT_OF ""
set_interface_property i2c_port PORT_NAME_MAP ""
set_interface_property i2c_port CMSIS_SVD_VARIABLES ""
set_interface_property i2c_port SVD_ADDRESS_GROUP ""

add_interface_port i2c_port SCL scl Output 1
add_interface_port i2c_port SDA sda Bidir 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint slave
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1

